/**
 * Branded primitives the domain passes around.
 *
 * A brand costs nothing at runtime and makes the two mistakes this codebase is
 * most exposed to into compile errors: passing a wall-clock millisecond value
 * where a chain timestamp in seconds belongs, and passing a region subject code
 * where an enum ordinal belongs (see CONTRACT_DEFECTS.md — those two differ for
 * 50 of 98 regions and a wrong one silently addresses a different real region).
 *
 * Every constructor validates. There is no unchecked cast helper on purpose: if
 * a value reaches here unvalidated, the boundary that let it in is the bug.
 */

declare const brand: unique symbol;

type Brand<T, B extends string> = T & { readonly [brand]: B };

/** A Unix timestamp in **seconds**. Chain block time, never `Date.now()`. */
export type UnixSeconds = Brand<number, 'UnixSeconds'>;

/** An EIP-155 chain identifier. */
export type ChainId = Brand<number, 'ChainId'>;

/**
 * A 20-byte Ethereum address in `0x`-prefixed hex.
 *
 * Case is preserved rather than normalized: EIP-55 checksum casing is
 * information, and verifying it needs keccak, which is a chain-adapter
 * capability. This type asserts shape only.
 */
export type EvmAddress = Brand<string, 'EvmAddress'>;

/**
 * The app's own reference for one governance operation. Printed on an issued
 * form and the only key by which app-authored context is recovered when that
 * form comes back — never read from the returned file itself.
 */
export type OperationRef = Brand<string, 'OperationRef'>;

export class InvalidPrimitiveError extends Error {
  constructor(what: string, received: unknown) {
    super(`${what}: received ${JSON.stringify(received) ?? String(received)}`);
    this.name = 'InvalidPrimitiveError';
  }
}

const isNonNegativeInteger = (value: number): boolean =>
  Number.isSafeInteger(value) && value >= 0;

export function unixSeconds(value: number): UnixSeconds {
  if (!isNonNegativeInteger(value)) {
    throw new InvalidPrimitiveError(
      'a Unix timestamp must be a non-negative safe integer count of seconds',
      value,
    );
  }
  return value as UnixSeconds;
}

export function chainId(value: number): ChainId {
  if (!isNonNegativeInteger(value) || value === 0) {
    throw new InvalidPrimitiveError(
      'a chain id must be a positive safe integer',
      value,
    );
  }
  return value as ChainId;
}

const EVM_ADDRESS_PATTERN = /^0x[0-9a-fA-F]{40}$/;

export function evmAddress(value: string): EvmAddress {
  if (!EVM_ADDRESS_PATTERN.test(value)) {
    throw new InvalidPrimitiveError(
      'an address must be 0x followed by 40 hex characters',
      value,
    );
  }
  return value as EvmAddress;
}

/**
 * `operationRef` values are generated by an {@link IdGenerator} adapter, so the
 * only shape rule enforced here is the one that keeps a reference usable as a
 * storage key and printable on a form: non-empty, no surrounding whitespace,
 * and bounded so a hostile form cannot present a megabyte-long "reference".
 */
const OPERATION_REF_MAX_LENGTH = 128;

export function operationRef(value: string): OperationRef {
  if (
    value.length === 0 ||
    value.length > OPERATION_REF_MAX_LENGTH ||
    value.trim() !== value
  ) {
    throw new InvalidPrimitiveError(
      `an operation reference must be 1..${OPERATION_REF_MAX_LENGTH} characters with no surrounding whitespace`,
      value,
    );
  }
  return value as OperationRef;
}
